# -*- coding: utf-8 -*-
"""1_Introduction_to_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13dn3CEMfwoE7yvd6QLyLT--nTkE_Nfd1
"""

print("hello world") #m1 : run by clicking on play buttom

print("hello")  #m2 : Run by pressing ctrl + enter = m1

print("Hi") #m3 : Run by pressing shift + enter = add code block also by running